#!/usr/bin/env node
/**
 * Script to import Reina Valera 1909 Bible into Supabase
 *
 * Usage:
 *   node scripts/import_bible_verses.js > bible_inserts.sql
 *
 * Then run the SQL in Supabase SQL Editor or via CLI
 */

const https = require('https');

// Bible JSON URL (Reina Valera - public domain)
const BIBLE_URL = 'https://raw.githubusercontent.com/thiagobodruk/bible/master/json/es_rvr.json';

// Mapping from source abbreviations to standard 3-letter codes
// Source uses lowercase 2-letter codes, we need uppercase 3-letter
const BOOK_MAPPING = {
  // Old Testament
  'gn': { id: 'GEN', name: 'Génesis' },
  'ex': { id: 'EXO', name: 'Éxodo' },
  'lv': { id: 'LEV', name: 'Levítico' },
  'nm': { id: 'NUM', name: 'Números' },
  'dt': { id: 'DEU', name: 'Deuteronomio' },
  'js': { id: 'JOS', name: 'Josué' },
  'jud': { id: 'JDG', name: 'Jueces' },
  'rt': { id: 'RUT', name: 'Rut' },
  '1sm': { id: '1SA', name: '1 Samuel' },
  '2sm': { id: '2SA', name: '2 Samuel' },
  '1rs': { id: '1KI', name: '1 Reyes' },
  '2rs': { id: '2KI', name: '2 Reyes' },
  '1cr': { id: '1CH', name: '1 Crónicas' },
  '2cr': { id: '2CH', name: '2 Crónicas' },
  'ed': { id: 'EZR', name: 'Esdras' },
  'ne': { id: 'NEH', name: 'Nehemías' },
  'et': { id: 'EST', name: 'Ester' },
  'job': { id: 'JOB', name: 'Job' },
  'sl': { id: 'PSA', name: 'Salmos' },
  'pv': { id: 'PRO', name: 'Proverbios' },
  'ec': { id: 'ECC', name: 'Eclesiastés' },
  'ct': { id: 'SNG', name: 'Cantares' },
  'is': { id: 'ISA', name: 'Isaías' },
  'jr': { id: 'JER', name: 'Jeremías' },
  'lm': { id: 'LAM', name: 'Lamentaciones' },
  'ez': { id: 'EZK', name: 'Ezequiel' },
  'dn': { id: 'DAN', name: 'Daniel' },
  'os': { id: 'HOS', name: 'Oseas' },
  'jl': { id: 'JOL', name: 'Joel' },
  'am': { id: 'AMO', name: 'Amós' },
  'ob': { id: 'OBA', name: 'Abdías' },
  'jn': { id: 'JON', name: 'Jonás' },
  'mq': { id: 'MIC', name: 'Miqueas' },
  'na': { id: 'NAM', name: 'Nahúm' },
  'hc': { id: 'HAB', name: 'Habacuc' },
  'sf': { id: 'ZEP', name: 'Sofonías' },
  'ag': { id: 'HAG', name: 'Hageo' },
  'zc': { id: 'ZEC', name: 'Zacarías' },
  'ml': { id: 'MAL', name: 'Malaquías' },
  // New Testament
  'mt': { id: 'MAT', name: 'Mateo' },
  'mc': { id: 'MRK', name: 'Marcos' },
  'lc': { id: 'LUK', name: 'Lucas' },
  'jo': { id: 'JHN', name: 'Juan' },
  'at': { id: 'ACT', name: 'Hechos' },
  'rm': { id: 'ROM', name: 'Romanos' },
  '1co': { id: '1CO', name: '1 Corintios' },
  '2co': { id: '2CO', name: '2 Corintios' },
  'gl': { id: 'GAL', name: 'Gálatas' },
  'ef': { id: 'EPH', name: 'Efesios' },
  'fp': { id: 'PHP', name: 'Filipenses' },
  'cl': { id: 'COL', name: 'Colosenses' },
  '1ts': { id: '1TH', name: '1 Tesalonicenses' },
  '2ts': { id: '2TH', name: '2 Tesalonicenses' },
  '1tm': { id: '1TI', name: '1 Timoteo' },
  '2tm': { id: '2TI', name: '2 Timoteo' },
  'tt': { id: 'TIT', name: 'Tito' },
  'fm': { id: 'PHM', name: 'Filemón' },
  'hb': { id: 'HEB', name: 'Hebreos' },
  'tg': { id: 'JAS', name: 'Santiago' },
  '1pe': { id: '1PE', name: '1 Pedro' },
  '2pe': { id: '2PE', name: '2 Pedro' },
  '1jo': { id: '1JN', name: '1 Juan' },
  '2jo': { id: '2JN', name: '2 Juan' },
  '3jo': { id: '3JN', name: '3 Juan' },
  'jd': { id: 'JUD', name: 'Judas' },
  'ap': { id: 'REV', name: 'Apocalipsis' },
  're': { id: 'REV', name: 'Apocalipsis' }  // Alternative abbreviation
};

function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          // Remove BOM if present
          if (data.charCodeAt(0) === 0xFEFF) {
            data = data.slice(1);
          }
          resolve(JSON.parse(data));
        } catch (e) {
          reject(e);
        }
      });
    }).on('error', reject);
  });
}

function escapeSQL(str) {
  // Escape single quotes for SQL
  return str.replace(/'/g, "''");
}

async function main() {
  console.error('Downloading Bible JSON...');
  const books = await fetchJSON(BIBLE_URL);
  console.error(`Found ${books.length} books`);

  let totalVerses = 0;
  const inserts = [];

  // Begin transaction
  console.log('-- Reina Valera Bible Import');
  console.log('-- Generated by scripts/import_bible_verses.js');
  console.log('-- Total books: ' + books.length);
  console.log('');
  console.log('BEGIN;');
  console.log('');

  for (const book of books) {
    const abbrev = book.abbrev.toLowerCase();
    const mapping = BOOK_MAPPING[abbrev];

    if (!mapping) {
      console.error(`WARNING: Unknown book abbreviation: ${abbrev}`);
      continue;
    }

    const bookId = mapping.id;
    const bookName = mapping.name;

    console.log(`-- ${bookName} (${bookId})`);

    // chapters is an array of arrays (each chapter contains verse strings)
    for (let chapterIdx = 0; chapterIdx < book.chapters.length; chapterIdx++) {
      const chapter = book.chapters[chapterIdx];
      const chapterNum = chapterIdx + 1; // 1-indexed

      for (let verseIdx = 0; verseIdx < chapter.length; verseIdx++) {
        const verseText = chapter[verseIdx];
        const verseNum = verseIdx + 1; // 1-indexed

        if (!verseText || verseText.trim() === '') {
          continue;
        }

        const sql = `INSERT INTO bible_verses (book_id, book_name, chapter, verse, text) VALUES ('${bookId}', '${escapeSQL(bookName)}', ${chapterNum}, ${verseNum}, '${escapeSQL(verseText.trim())}');`;
        console.log(sql);
        totalVerses++;
      }
    }
    console.log('');
  }

  console.log('COMMIT;');
  console.log('');
  console.log(`-- Total verses inserted: ${totalVerses}`);

  console.error(`Done! Total verses: ${totalVerses}`);
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
