-- Migration: Add verse_summary column to daily_verse_texts
-- This column stores a colloquial summary of the gospel generated by AI

ALTER TABLE public.daily_verse_texts
ADD COLUMN verse_summary text;

COMMENT ON COLUMN public.daily_verse_texts.verse_summary IS
'Resumen del evangelio en lenguaje coloquial, generado por IA';
